### PR TITLE
Convert Discord bot to aws lambda

### PR DESCRIPTION
**Pull request by marc-aurele-besner**
## Convert Discord bot to aws lambda

- Implement aws-lambda handler
- Use discord rest instead of a client listening to the server interaction
- Implement faunadb for a minimal db to persist user's requests and stats
- Add more rigid spam protection, to make sure the same user does not request tokens over and over to different addresses

### CODE REVIEW

**Review by EmilFattakhov — COMMENTED** [review]
Looks great at a glance, thanks @marc-aurele-besner! Let me try running a quick deployment and get back to you!

**Comment by jfrank-summit** [comment]
@EmilFattakhov Were you able to run a deployment?

**Comment by EmilFattakhov** [comment]
Hey @marc-aurele-besner, @jfrank-summit, I gave it a try on Tuesday and wasn't able to complete the deployment, will give it another try tomorrow morning. Been busy the last couple of days, sorry about the delay!
@marc-aurele-besner I will slack you tomorrow, we might need to have a look together.

**Review by EmilFattakhov — DISMISSED** [review]
Thank you @marc-aurele-besner for all your help with deployment, everything works as expected!

**Review by EmilFattakhov — APPROVED** [review]
Looks great @marc-aurele-besner!

**Pull request merged**
